version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - postgres.env
    environment:
      - MAIL_FROM=noreply@sigterm.no
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USER=noreply@sigterm.no
      - MAIL_PASS=
      - MAIL_PORT=587
      - MAIL_TLS=True
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    env_file:
      - postgres.env
